### ISSUE TITLE
Certificate error using given example in Readme.md

### ISSUE THREAD

**Issue by evandrojr** [greyblake/crystal-google_translate#3]
SSL_connect: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed (OpenSSL::SSL::Error)
  from /usr/share/crystal/src/openssl/ssl/socket.cr:34:9 in 'initialize'
  from OpenSSL::SSL::Socket::Client::new:context:sync_close:hostname<TCPSocket, OpenSSL::SSL::Context::Client, Bool, String>:OpenSSL::SSL::Socket::Client
  from /usr/share/crystal/src/http/client.cr:657:5 in 'socket'
  from /usr/share/crystal/src/http/client.cr:500:5 in 'exec_internal_single'
  from /usr/share/crystal/src/http/client.cr:486:5 in 'exec_internal'
  from /usr/share/crystal/src/http/client.cr:482:5 in 'exec'
  from /usr/share/crystal/src/http/client.cr:585:5 in 'exec'
  from lib/cossack/src/cossack/connection/http_connection.cr:9:23 in 'call'
  from lib/cossack/src/cossack/client.cr:44:7 in 'call'
  from lib/cossack/src/cossack/client.cr:47:5 in 'get'
  from lib/google_translate/src/google_translate/client.cr:49:23 in 'raw_translate'
  from lib/google_translate/src/google_translate/client.cr:22:23 in 'translate'
  from src/crystal-sub-translator.cr:7:3 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:11:3 in '_crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:112:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:101:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:135:3 in 'main'
  from __libc_start_main
  from _start
  from ???

**Comment by evandrojr** [comment]
Pull Request submited #2

**Comment by greyblake** [comment]
Closed with https://github.com/greyblake/crystal-google_translate/pull/2
